### ISSUE TITLE
Práctica 6

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-6-practica-de-productividad-busgs-pull-request-equipo-ycej#1]
[Práctica 6.-Edwin_Yanet_Carlos_Jeronima.pdf](https://github.com/user-attachments/files/17237046/Practica.6.-Edwin_Yanet_Carlos_Jeronima.pdf)

**Comment by josealfredo79** [comment]
Calificacion...????

**Comment by ka194** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
En esta practica falta la creacion de la nueva rama, pull request, el merge...el cierre automatico de la incidencia...

**Comment by ka194** [comment]
Calificación: 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
